apiVersion: v1
kind: Service
metadata:
  name: postcodesio
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    app: postcodesio
